# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-06-10 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('billing_type', models.CharField(blank=True, choices=[(b'monthly', b'Monthly'), (b'yearly', b'Yearly')], max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[(b'stripe', b'Stripe'), (b'paypal', b'Paypal')], max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_refund', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[(b'basic', b'Basic'), (b'premium', b'Premium')], max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.AddField(
            model_name='customerplan',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.SubscriptionPlan'),
        ),
    ]
