# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-06-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplan',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
